title: libexactreal
authors:
  - "<a href='https://github.com/videlec'>Vincent Delecroix</a>"
  - "<a href='https://github.com/saraedum'>Julian Rüth</a>"
description: >-
  exact-real is a collection of libraries to work with finite submodules of
  \(\mathbb{R}\). libexactreal is the C++ core of exact-real.
baseurl: "/exact-real"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: flatsurf

header_pages:
  - None

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-optional-front-matter
